name: mlflow-presentations
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - aif360>=0.6.1
  - imbalanced-learn>=0.0  # imblearn package is called imbalanced-learn in conda
  - mlflow>=2.20.2
  - notebook>=7.3.2
  - scikit-learn>=1.6.1
  - shap>=0.46.0
  - xgboost>=2.1.4
  - seaborn